# Generated by Django 2.2.3 on 2019-07-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0002_post_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='imagem_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/fotoperfil/'),
        ),
    ]
